config/routes.rb
Rails.application.routes.draw do
  get 'my_pokemons/search'
  post 'my_pokemons/trade'
  resources :my_pokemons

  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :my_pokemons, only: %i[index new create show search edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_pokemon.rb
class MyPokemon < ApplicationRecord
  belongs_to :pokemon
  belongs_to :user
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :my_pokemons

  TYPES = %w[fire water grass rock ground bug ice flying fighting fairy dragon electric steel poison normal ghost dark psychic].freeze

  validates :name, presence: true
  validates :type_1, inclusion: { in: TYPES }, presence: true
  validates :type_2, inclusion: { in: TYPES }, exclusion: { in: ->(pokemon) { [pokemon.type_1] } }, allow_nil: true, allow_blank: true
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :my_pokemon

# belongs_to :pokemon1, :class_name => "Pokemon"
# belongs_to :pokemon2, :class_name => "Pokemon"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :my_pokemons, dependent: :destroy
  has_many :trades, dependent: :destroy

  validates :first_name, :last_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: :home

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def home
  end
end

app/controllers/my_pokemons_controller.rb
class MyPokemonsController < ApplicationController

  def index
    @my_pokemons = current_user.my_pokemons.all
  end

  def search
    @trade_pokemons = MyPokemon.where(available: true).where.not(user: current_user)
  end

  def edit
    @my_trade_pokemons = MyPokemon.where(available: true).where(user: current_user)
    @other_pokemon_id = params[:id]
  end

  def update
    my_pokemon = MyPokemon.find(params[:id])
    other_pokemon = MyPokemon.find(params[:other_pokemon_id])
    my_pokemon_user = my_pokemon.user
    my_pokemon.user = other_pokemon.user
    my_pokemon.save
    other_pokemon.user = my_pokemon_user
    other_pokemon.save
    redirect_to root_path
  end

  def show
  end

  def new
    @my_pokemon = MyPokemon.new
  end

  def create
    @my_pokemon = MyPokemon.new
    @pokemon = Pokemon.find(params[:my_pokemon][:pokemon_id])
    @my_pokemon.pokemon = @pokemon
    @my_pokemon.user = current_user
    if @my_pokemon.save
      redirect_to my_pokemons_path
    else
      render :new
    end
  end

  def destroy
    @my_pokemon = MyPokemon.find(params[:id])
    @my_pokemon.destroy
    redirect_to my_pokemons_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to my_pokemons_path if user_signed_in?
  end

  def profile
    @pokemon.name
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[show]

  def index
    @pokemons = user.pokemons.all
  end

  def show
  end

  private

  def pokemon_params
    params.require(:trade).permit(:name, :type_1, :type_2, :image_url)
  end

  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_my_pokemon, only: %i[show destroy]

  def index
    @my_pokemons = current_user.my_pokemons.all
  end

  def show
  end

  def new
    @my_pokemon = MyPokemon.new
  end

  def create
    @my_pokemon = MyPokemon.new
    @pokemon = Pokemon.find(params[:my_pokemon][:pokemon_id])
    @my_pokemon.pokemon = @pokemon
    @my_pokemon.user = current_user
    if @my_pokemon.save
      redirect_to my_pokemons_path
    else
      render :new
    end
  end

  private

  def set_my_pokemon
    @my_pokemon = MyPokemon.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokeplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  </head>

  <body>

    <% unless current_page?(root_path) || current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
      <%= render 'shared/navbar' %>
    <% end %>

    <%= render 'shared/flashes' %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/my_pokemons/edit.html.erb
<div class="container pt-4 pb-4">
  <h1 class="text-center"> Trade </h1>
  <div class="container d-flex align-items-center flex-wrap justify-content-center mb-5">
    <% @my_trade_pokemons.each do |my_pokemon| %>
      <div class="card col-3 d-flex flex-column mt-5 mb-3">
        <div class="picture">
          <%= image_tag(my_pokemon.pokemon.image_url) %>
        </div>
        <div class="content d-flex">
          <div class="col">
            <%= my_pokemon.pokemon.name %>
          </div>
          <div class="col d-flex justify-content-end">
            <span>
                <%= my_pokemon.pokemon.type_1 %>
            </span>
            <% unless my_pokemon.pokemon.type_2.nil? %>
              <span>
                <%= my_pokemon.pokemon.type_2 %>
              </span>
            <% end %>
          </div>
        </div>
        <%= simple_form_for my_pokemon do |f| %>
          <%= hidden_field_tag :other_pokemon_id, @other_pokemon_id %>
          <%= f.submit "trade", class: "btn btn-primary w-100 mt-2 rounded-pill" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/my_pokemons/index.html.erb
<div class="container pt-4 pb-4">
  <h1 class="text-center"> Pokedex </h1>
  <div class="container d-flex flex-row flex-wrap justify-content-center">
    <% @my_pokemons.each do |my_pokemon| %>
      <div class="card col-3 d-flex flex-collumn mt-5 mb-3">
        <div class="picture">
          <%= image_tag(my_pokemon.pokemon.image_url) %>
          <div class="trash">
            <%=link_to my_pokemon_path(my_pokemon),data: { confirm: 'Are you sure you want to delete this item?' }, method: :delete do %>
              <i class="fas fa-trash-alt" ></i>
            <% end %>
          </div>
        </div>
        <div class="content d-flex">
          <div class="col">
            <%= my_pokemon.pokemon.name %>
          </div>
          <div class="col d-flex justify-content-end">
            <span>
                <%= my_pokemon.pokemon.type_1 %>
            </span>
            <% unless my_pokemon.pokemon.type_2.nil? %>
              <span>
                <%= my_pokemon.pokemon.type_2 %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/my_pokemons/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a Pokémon</h3>
        <%= simple_form_for @my_pokemon do |f| %>
          <%= f.input :pokemon_id, collection: Pokemon.all.order(:name), input_html: { data: { controller: 'select2' }} %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/my_pokemons/search.html.erb
<div class="container pt-4 pb-4">
  <h1 class="text-center"> Pokedex </h1>
  <div class="container d-flex align-items-center flex-wrap justify-content-center mb-5">
    <% @trade_pokemons.each do |my_pokemon| %>
      <div class="card col-3 d-flex flex-column mt-5 mb-3">
        <div class="picture">
          <%= image_tag(my_pokemon.pokemon.image_url) %>
        </div>
        <div class="content d-flex">
          <div class="col">
            <%= my_pokemon.pokemon.name %>
          </div>
          <div class="col d-flex justify-content-end">
            <span>
                <%= my_pokemon.pokemon.type_1 %>
            </span>
            <% unless my_pokemon.pokemon.type_2.nil? %>
              <span>
                <%= my_pokemon.pokemon.type_2 %>
              </span>
            <% end %>
          </div>
        </div>
        <div>
          <%= link_to "trade", edit_my_pokemon_path(my_pokemon), class: "btn btn-primary w-100 mt-2 rounded-pill" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/my_pokemons/show.html.erb
<h1>MyPokemons#show</h1>
<p>Find me in app/views/my_pokemons/show.html.erb</p>

app/views/my_pokemons/trade.html.erb
<%# sem uso %>

<h1 class="title is-1">Trades</h1>

<div class="container pt-4">
  <h1 class="text-center"> Pokedex </h1>
  <div class="container d-flex align-items-center flex-wrap justify-content-center">
    <% @my_trade_pokemons.each do |my_trade_pokemon| %>
      <div class="card col-3 d-flex flex-column">
        <div class="picture">
          <%= image_tag(my_pokemon.pokemon.image_url) %>
        </div>
        <div class="content d-flex">
          <div class="col">
            <%= my_trade_pokemon.pokemon.name %>
          </div>
          <div class="col d-flex justify-content-end">
            <span>
                <%= my_trade_pokemon.pokemon.type_1 %>
            </span>
            <% unless my_trade_pokemon.pokemon.type_2.nil? %>
              <span>
                <%= my_trade_pokemon.pokemon.type_2 %>
              </span>
            <% end %>
          </div>
        </div>
      <%= link_to "trade", edit_my_pokemon_path(my_trade_pokemon), class: "btn btn-primary w-100 rounded-pill d-inline-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="homepage container-fluid">
  <div>
    <%= image_tag "home-banner.png", class: "banner-bg" %>
  </div>

  <div>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-dark" %>
    <%= link_to "Register", new_user_registration_path, class: "btn btn-outline-dark" %>
  </div>
</div>

app/views/pokemons/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center">
    <h1>Trade Pokémons</h1>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Pokémons</h3>
    <%= link_to "Add a Pokémon to your list", new_pokemon_path, class: "btn btn-flat" %>
  </div>
</div>

<% @pokemons.each do |pokemon| %>
  <%= pokemon.name %>
  <%= pokemon.type_1 %>
  <%= pokemon.type_2 if pokemon.type_2 %>
<% end %>

app/views/pokemons/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a Pokémon</h3>
        <%= simple_form_for @pokemon do |f| %>
          <%= f.input :name %>
          <%= f.input :type_1 %>
          <%= f.input :type_2, :input_html => { :value => nil} %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Search a Pokémon</h3>
        <%= simple_form_for @c do |f| %>
          <%= f.input :pokemon_id, collection: Pokemon.all.order(:name), input_html: { data: { controller: 'select2' }} %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://w7.pngwing.com/pngs/620/521/png-transparent-poke-ball-pokemon-pokemon-rim-mobile-phones-pokemon.png", class: "nav-icon" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse mb-3" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li >
            <%= link_to "Search", my_pokemons_search_path, class: "nav-link" %>
          <li>
            <%=link_to "Add Pokémon", new_my_pokemon_path, class: "nav-link btn btn-add"%>
          </li>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://img2.gratispng.com/20180202/djw/kisspng-ash-ketchum-hat-cap-red-and-white-baseball-cap-5a74a96a19a279.130418901517594986105.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>